version: 0.2
env:
  variables:
    STAFF_IDENTITY_TABLE: staff-identity-service
    STAFF_SESSIONS_TABLE: staff-service-sessions
    LAMBDA_FUNCTION_NAME: staff-identity-service-function
    STAFF_IDENTITY_TABLE_SUB_INDEX: cognitoSub-index
    STAFF_WS_CONNECTION_TABLE: staff-service-websocket-connections
    WEB_SOCKET_ENDPOINT: https://l95ib78653.execute-api.ap-south-1.amazonaws.com/dev
  parameter-store:
    USERPOOL_ID: '/dev/staff/USER_POOL_ID'
    USERPOOL_CLIENT_ID: '/dev/staff/USER_POOL_CLIENTID'

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  pre_build:
    commands:
      - echo Staring the pre build stage
      - touch .env
      - echo "USER_POOL_ID=$USERPOOL_ID" >> .env
      - echo "USER_POOL_CLIENT_ID=$USERPOOL_CLIENT_ID" >> .env
      - echo "STAFF_IDENTITY_TABLE=$STAFF_IDENTITY_TABLE" >> .env
      - echo "STAFF_IDENTITY_TABLE_SUB_INDEX=$STAFF_IDENTITY_TABLE_SUB_INDEX" >> .env
      - echo "STAFF_SESSIONS_TABLE=$STAFF_SESSIONS_TABLE" >> .env
      - echo "STAFF_WS_CONNECTION_TABLE=$STAFF_WS_CONNECTION_TABLE" >> .env
      - echo "WEB_SOCKET_ENDPOINT=$WEB_SOCKET_ENDPOINT" >> .env
  build:
    commands:
      - echo zipping lambda code
      - zip -r lambda_code.zip . -x ".git/*"
      - echo zipped lambda code
      - ls -lrth
      - echo uploading lambda code
      - aws s3 cp lambda_code.zip s3://codebuild-trouver/
      - echo uploaded lambda code
  post_build:
    commands:
      - echo deploying lambda function
      - aws lambda update-function-code --function-name  $LAMBDA_FUNCTION_NAME --s3-bucket codebuild-trouver --s3-key lambda_code.zip
